title: James Vall√©e Portfolio
baseurl: ""
url: "https://jamesvallee.ca"
theme: minima
collections:
  fsae:
    output: true
    permalink: /fsae/:name/
  personal:
    output: true
    permalink: /personal/:name/
